[run]
source = ["src"]
omit = [
    "tests/*",
    "**/__pycache__/*",
    "**/conftest.py",
    "**/__init__.py",
]

[report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "@abstractmethod",
]
show_missing = true
skip_covered = false

[xml]
output = "coverage.xml